### ISSUE TITLE
29 january launch revision

### ISSUE THREAD

**Issue by vecna** [tracking-exposed/eu19#3]
the goal of the day is having a work in progress page on eu19.tracking.exposed

I push in the new branch, named 29-January-Release this page, if would be the homepage:  https://github.com/tracking-exposed/eu19/blob/29-January-Release/content/page/introduction.md 

The goal of today is **having this page up an accessible at 16**, and probably this would only be used in the next three-four days. When we have the definitive content, it would be replaced.

### Two things can be done

@shannoncunningham please give a look to the text. It lack of links. If you see any section/keyword which can be linked (like, ALEX -> https://erc.europa.eu/news/erc-proof-concept-grant-examples-research-projects-2-round ), put them in markdown format. Push in a different branch and to the pull request, we can try the process. The text should be considered reviewed enough, but it is intended to be a speech, if you see something which can be shaped differently, feel free to fix it.
 
@lrnzctld please remove the "hero" word from the bar and upload the content in the webserver online, the home directory of the user is the root www of the webserver.

thanks!

### FYI, the top of the page looks like this now

![image](https://user-images.githubusercontent.com/89555/51892418-21305300-23a2-11e9-91a8-f38d14da5912.png)

**Comment by shannoncunningham** [comment]
Since I know you're incredibly busy right now, here's a quick list of what's been done so far, and what's still waiting on inputs. I don't at all want to detract time from planning and coding the actual tools and site, but I also don't want to be idle if there's any way I can help us prepare, so whatever timeframe you're comfortable with/whenever you have moments to provide inputs on these, I'll get to them right away. I don't want to rush you on my end at all, take your time with me. :)

Based on draft website tabs to-do list:

**Landing page**
- [x] EU19 talk as edited for homepage?

**Internals / stats / open data / tech**
- [ ] Waiting for inputs

**Research / workshop**
- [x] Text prepared
- [ ] Waiting for documentation
- [ ] (report + presentation of WS DMI)

**Individual**
- [x] Text prepared
- [ ] CTA if you want to learn data/code go to the next tab
*I think this is the Internals / stats / open data / tech tab, so I’m not sure where to direct yet*
- [ ] Waiting for current UX to embed/represent

**Candidates**
- [x] Text prepared

**Project goal**
- [ ] Short/medium/long term goal
- [ ] Ethos
*If I remember correctly, you wanted to give inputs both of these, so I’ve been holding off*

**RSS “pop your bubble”**
- [x] Text prepared
- [x] RSS description, clients and article included
- [x] SOCMINT covered lightly
- [ ] SOCMINT link 
*I think you wanted to have some input on which link to use about SOCMINT information – I can try to find something, if you’d like*

**Blow the whistle**
- [ ] Waiting for legal language choice input, if I remember correctly
- [ ] Waiting for security tips

**Comment by vecna** [comment]
on SOCMINT link https://responsibledata.io/social-media-intelligence-the-wayward-child-of-open-source-intelligence/

**Comment by vecna** [comment]
- the blow the whistle section would appear later, don't wait for this now. 
- ethos can be the section _Self-imposed limitations and data ethics_ of https://github.com/tracking-exposed/presentation/raw/master/fbTREX%20-%20project%20status%20and%20analysis%20-%20December%202018.pdf

**Comment by berli0z** [comment]
> **Research / workshop**
>     * [ ]  Waiting for documentation
Should i prepare a small introduction? under tree/texts/workshop_intro? or is it this: https://github.com/tracking-exposed/eu19/blob/texts/researcher-text.md ?

>     * [ ]  (report + presentation of WS DMI)
here is the link to the slides, report is not available yet: https://docs.google.com/presentation/d/1lY2oFkcKGP7Wa-EnDAEZsxMd6Riy7g3-AQZNY8AflcY/edit#slide=id.p

**Comment by vecna** [comment]
- the blow the whistle section would appear later, don't wait for this now. 
- ethos can be the section _Self-imposed limitations and data ethics_ of https://github.com/tracking-exposed/presentation/raw/master/fbTREX%20-%20project%20status%20and%20analysis%20-%20December%202018.pdf

**Comment by vecna** [comment]
I imported your texts in page to be published, and moved the work in progress in 'texts-wip' directory.

**Comment by vecna** [comment]
@berli0z yes, the researcher text (now in content/page/ directory) would benefit of your contribution, thanks

**Comment by vecna** [comment]
happily outdated
